#!/bin/bash

echo '{
  "results": [
    {
      "name": "Invocations",
      "title": "Invocations",
      "unit": "count",
      "available_filters": ["scope_id"],
      "available_group_by": []
    }
  ]
}'
